Script started on Sat 07 May 2016 12:41:17 AM PDT
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from Pointer Explore...done.
[36m(gdb) [0mlist 1,11
1	int main(void) {
2	    int x[] = {10, 20, 30, 40, 99};
3	    int * y = x;
4	    int z = *y;
5	
6	    while (*y != 99) {
7	        z = *y++;
8	//      z = y[0]; y = y + 1;
9	    }
10	    return 0;
11	}
[36m(gdb) [0mbreak 7
Breakpoint 1 at 0x400527: file Pointer Explore.c, line 7.
[36m(gdb) [0mrun
Starting program: /home/patrick.hawks1016/B13/Pointer Explore 

Breakpoint 1, main () at Pointer Explore.c:7
7	        z = *y++;
[36m(gdb) [0mdisplay y
1: y = (int *) 0x7fffffffe4f0
[36m(gdb) [0mdisplay *y
2: *y = 10
[36m(gdb) [0mdisplay z
3: z = 10
[36m(gdb) [0mstep
6	    while (*y != 99) {
3: z = 10
2: *y = 20
1: y = (int *) 0x7fffffffe4f4
[36m(gdb) [0mstep

Breakpoint 1, main () at Pointer Explore.c:7
7	        z = *y++;
3: z = 10
2: *y = 20
1: y = (int *) 0x7fffffffe4f4
[36m(gdb) [0mcontinue
Continuing.

Breakpoint 1, main () at Pointer Explore.c:7
7	        z = *y++;
3: z = 20
2: *y = 30
1: y = (int *) 0x7fffffffe4f8
[36m(gdb) [0mcontinue
Continuing.

Breakpoint 1, main () at Pointer Explore.c:7
7	        z = *y++;
3: z = 30
2: *y = 40
1: y = (int *) 0x7fffffffe4fc
[36m(gdb) [0mcontinue
Continuing.
[Inferior 1 (process 15427) exited normally]
[36m(gdb) [0mq

Script done on Sat 07 May 2016 12:42:00 AM PDT
